"""Strategy PDF export. Renders only persisted, evidence-backed data."""

from __future__ import annotations

import io
from datetime import UTC, datetime
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

DISCLAIMER = (
    "This report summarizes research results generated by AdmitGraph. Every claim is backed by "
    "source evidence with retrieval timestamps; UNKNOWN fields were not verifiable at generation "
    "time. Confirm all requirements, costs and deadlines with the official source before making "
    "decisions. This document does not state or imply any admission probability."
)

_CATEGORY_COLORS = {
    "REACH": colors.HexColor("#FDE8E8"),
    "TARGET": colors.HexColor("#FEF3C7"),
    "LOWER_RISK": colors.HexColor("#DCFCE7"),
}

_SEVERITY_COLORS = {
    "CRITICAL": colors.HexColor("#FECACA"),
    "HIGH": colors.HexColor("#FED7AA"),
    "MEDIUM": colors.HexColor("#FEF9C3"),
    "LOW": colors.HexColor("#E5E7EB"),
}


def _styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("t", parent=base["Title"], fontSize=18, spaceAfter=4),
        "meta": ParagraphStyle("m", parent=base["Normal"], fontSize=9, textColor=colors.grey),
        "h2": ParagraphStyle("h2", parent=base["Heading2"], fontSize=13, spaceBefore=12),
        "body": ParagraphStyle("b", parent=base["Normal"], fontSize=9, leading=12),
        "small": ParagraphStyle("s", parent=base["Normal"], fontSize=8, leading=10),
    }


def _cell(text: Any, style: ParagraphStyle) -> Paragraph:
    return Paragraph(str(text) if text is not None else "—", style)


def render_strategy_pdf(payload: dict[str, Any]) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=1.5 * cm,
        rightMargin=1.5 * cm,
        topMargin=1.5 * cm,
        bottomMargin=1.5 * cm,
        title=f"AdmitGraph Strategy {payload.get('strategy_id', '')}",
    )
    s = _styles()
    story: list[Any] = []

    story.append(Paragraph("AdmitGraph Strategy Report", s["title"]))
    generated = datetime.now(UTC).isoformat(timespec="seconds")
    story.append(
        Paragraph(
            f"Strategy {payload.get('strategy_id')} · generated {generated} "
            f"· plan health {payload.get('plan_health_score') or 'n/a'} · "
            f"scoring {payload.get('scoring_version')} · {payload.get('summary') or ''}",
            s["meta"],
        )
    )
    story.append(Spacer(1, 6))
    story.append(Paragraph(DISCLAIMER, s["small"]))
    story.append(Spacer(1, 10))

    # Portfolio
    story.append(Paragraph("Portfolio", s["h2"]))
    portfolio = payload.get("portfolio") or []
    if portfolio:
        data = [["Tier", "#", "Program", "Institution", "Rationale"]]
        for p in portfolio:
            data.append(
                [
                    _cell(p.get("category"), s["small"]),
                    _cell(p.get("priority"), s["small"]),
                    _cell(p.get("program_name"), s["small"]),
                    _cell(p.get("institution"), s["small"]),
                    _cell(p.get("rationale"), s["small"]),
                ]
            )
        table = Table(data, colWidths=[2.2 * cm, 0.8 * cm, 5.5 * cm, 4.0 * cm, 5.0 * cm])
        style = [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#111827")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#D1D5DB")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]
        for i, p in enumerate(portfolio, start=1):
            bg = _CATEGORY_COLORS.get(p.get("category", ""))
            if bg:
                style.append(("BACKGROUND", (0, i), (-1, i), bg))
        table.setStyle(TableStyle(style))
        story.append(table)
    else:
        story.append(Paragraph("No programs were assigned to this strategy.", s["body"]))

    # Risks
    story.append(Paragraph("Risks", s["h2"]))
    risks = payload.get("risks") or []
    if risks:
        data = [["Severity", "Risk", "Recommended action"]]
        for r in risks:
            data.append(
                [
                    _cell(r.get("severity"), s["small"]),
                    _cell(r.get("title"), s["small"]),
                    _cell(r.get("recommended_action"), s["small"]),
                ]
            )
        table = Table(data, colWidths=[2.2 * cm, 6.5 * cm, 8.8 * cm])
        style = [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#111827")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#D1D5DB")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]
        for i, r in enumerate(risks, start=1):
            bg = _SEVERITY_COLORS.get(r.get("severity", ""), None)
            if bg:
                style.append(("BACKGROUND", (0, i), (-1, i), bg))
        table.setStyle(TableStyle(style))
        story.append(table)
    else:
        story.append(Paragraph("No open risks were flagged.", s["body"]))

    # Roadmap
    story.append(Paragraph("Next tasks", s["h2"]))
    tasks = payload.get("roadmap_tasks") or []
    if tasks:
        for t in tasks:
            due = f" — due {t['due_date']}" if t.get("due_date") else ""
            story.append(Paragraph(f"• {t.get('title')}{due}", s["body"]))
    else:
        story.append(Paragraph("No tasks generated.", s["body"]))

    story.append(Spacer(1, 14))
    story.append(Paragraph(DISCLAIMER, s["small"]))

    doc.build(story)
    return buf.getvalue()
