-- AdmitGraph PostgreSQL schema — DERIVED ARTEFACT, DO NOT HAND-EDIT.
-- Generated by backend/scripts/export_schema.py: alembic upgrade head
-- followed by pg_dump --schema-only, so this file can never diverge
-- from the Alembic history (PLAN ground rule 6).
--
-- Alembic head at export time: 3e58d2140fc9
-- Regenerate: python -m scripts.export_schema --url <scratch-db-url>  (docker exec -e PGPASSWORD=*** deployment-postgres-1 pg_dump -U admitgraph -h localhost -d schema_scratch)
--
-- Load into a FRESH database:  psql -f database/schema.sql
-- The stamp row below leaves alembic at head, so a later
-- `alembic upgrade head` is a no-op instead of a collision.
--
-- PostgreSQL database dump
--

\restrict xs1kk4dWReqbh2lAO1443sEyeIIobTtgnJzRck4GUb7DNPI3gpoKQYZF4H0YuCo

-- Dumped from database version 16.15 (Debian 16.15-1.pgdg13+2)
-- Dumped by pg_dump version 16.15 (Debian 16.15-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


--
-- Name: confidence_level; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.confidence_level AS ENUM (
    'HIGH',
    'MEDIUM',
    'LOW'
);


--
-- Name: evidence_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.evidence_status AS ENUM (
    'CURRENT',
    'STALE',
    'CONFLICTING',
    'UNAVAILABLE'
);


--
-- Name: program_category; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.program_category AS ENUM (
    'REACH',
    'TARGET',
    'LOWER_RISK'
);


--
-- Name: requirement_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.requirement_status AS ENUM (
    'SATISFIED',
    'PARTIAL',
    'NOT_SATISFIED',
    'UNKNOWN',
    'NOT_APPLICABLE',
    'CONFLICTING',
    'NEEDS_VERIFICATION'
);


--
-- Name: risk_severity; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.risk_severity AS ENUM (
    'CRITICAL',
    'HIGH',
    'MEDIUM',
    'LOW'
);


--
-- Name: risk_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.risk_status AS ENUM (
    'OPEN',
    'ACKNOWLEDGED',
    'RESOLVED',
    'DISMISSED'
);


--
-- Name: run_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.run_status AS ENUM (
    'QUEUED',
    'RUNNING',
    'SUCCEEDED',
    'PARTIAL',
    'FAILED',
    'CANCELLED'
);


--
-- Name: source_authority; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.source_authority AS ENUM (
    'OFFICIAL_UNIVERSITY',
    'OFFICIAL_GOVERNMENT',
    'OFFICIAL_ORGANIZATION',
    'ACCREDITED_BODY',
    'CREDIBLE_SECONDARY',
    'NEWS',
    'FORUM_SOCIAL',
    'UNKNOWN'
);


--
-- Name: task_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.task_status AS ENUM (
    'TODO',
    'IN_PROGRESS',
    'DONE',
    'BLOCKED',
    'SKIPPED'
);


--
-- Name: user_role; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.user_role AS ENUM (
    'STUDENT',
    'ADMIN'
);


--
-- Name: set_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
        BEGIN
          NEW.updated_at = now();
          RETURN NEW;
        END; $$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: alembic_version; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.alembic_version (
    version_num character varying(32) NOT NULL
);


--
-- Name: application_plans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.application_plans (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    strategy_run_id uuid NOT NULL,
    profile_id uuid NOT NULL,
    program_id uuid NOT NULL,
    category public.program_category NOT NULL,
    priority integer NOT NULL,
    fit_assessment_id uuid,
    rationale text NOT NULL,
    estimated_cost jsonb DEFAULT '{}'::jsonb NOT NULL,
    next_deadline date,
    next_action text,
    status text DEFAULT 'PLANNED'::text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    reasons jsonb DEFAULT '[]'::jsonb NOT NULL
);


--
-- Name: auth_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_tokens (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    purpose text NOT NULL,
    token_hash text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: counterfactual_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.counterfactual_runs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    profile_id uuid NOT NULL,
    base_strategy_run_id uuid,
    scenario_name text NOT NULL,
    modified_profile jsonb NOT NULL,
    result jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: countries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.countries (
    code character varying(2) NOT NULL,
    name text NOT NULL,
    region text,
    currency character varying(3),
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL
);


--
-- Name: documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documents (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    profile_id uuid NOT NULL,
    document_type text NOT NULL,
    status public.task_status DEFAULT 'TODO'::public.task_status NOT NULL,
    expires_at date,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    file_path text,
    file_name text,
    file_size integer
);


--
-- Name: education_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.education_records (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    profile_id uuid NOT NULL,
    institution_name text NOT NULL,
    country_code character varying(2),
    degree text NOT NULL,
    field_of_study text,
    start_date date,
    end_date date,
    grade_value numeric(8,3),
    grade_scale numeric(8,3),
    grade_type text,
    is_current boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: education_subjects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.education_subjects (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    education_record_id uuid NOT NULL,
    subject_name text NOT NULL,
    credits numeric(8,2),
    grade_value text,
    normalized_subject text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: eligibility_assessments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.eligibility_assessments (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    fit_assessment_id uuid NOT NULL,
    requirement_id uuid NOT NULL,
    status public.requirement_status NOT NULL,
    matched_value jsonb DEFAULT '{}'::jsonb NOT NULL,
    expected_value jsonb DEFAULT '{}'::jsonb NOT NULL,
    reason text NOT NULL,
    confidence public.confidence_level NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: eligibility_evidence; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.eligibility_evidence (
    eligibility_assessment_id uuid NOT NULL,
    evidence_id uuid NOT NULL
);


--
-- Name: evidence; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.evidence (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    source_id uuid NOT NULL,
    search_result_id uuid,
    claim_type text NOT NULL,
    subject_type text NOT NULL,
    subject_id uuid,
    claim text NOT NULL,
    normalized_claim text,
    snippet text,
    summary text,
    extracted_value jsonb DEFAULT '{}'::jsonb NOT NULL,
    authority_score numeric(5,2) DEFAULT '0'::numeric,
    confidence public.confidence_level DEFAULT 'LOW'::public.confidence_level NOT NULL,
    status public.evidence_status DEFAULT 'CURRENT'::public.evidence_status NOT NULL,
    retrieved_at timestamp with time zone DEFAULT now() NOT NULL,
    published_at timestamp with time zone,
    freshness_deadline timestamp with time zone,
    content_hash text,
    conflict_group_id uuid,
    extraction_model text,
    extraction_version text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: evidence_conflict_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.evidence_conflict_members (
    conflict_id uuid NOT NULL,
    evidence_id uuid NOT NULL
);


--
-- Name: evidence_conflicts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.evidence_conflicts (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    conflict_key text NOT NULL,
    description text NOT NULL,
    resolution_status text DEFAULT 'UNRESOLVED'::text NOT NULL,
    preferred_evidence_id uuid,
    resolution_reason text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    resolved_at timestamp with time zone
);


--
-- Name: experiences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.experiences (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    profile_id uuid NOT NULL,
    experience_type text NOT NULL,
    title text NOT NULL,
    organization text,
    description text,
    start_date date,
    end_date date,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: fit_assessments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fit_assessments (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    research_plan_id uuid,
    profile_id uuid NOT NULL,
    program_id uuid NOT NULL,
    academic_score numeric(5,2),
    prerequisite_score numeric(5,2),
    language_score numeric(5,2),
    financial_score numeric(5,2),
    career_score numeric(5,2),
    timing_score numeric(5,2),
    evidence_confidence_score numeric(5,2),
    overall_score numeric(5,2) NOT NULL,
    scoring_version text NOT NULL,
    explanation text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    profile_snapshot jsonb DEFAULT '{}'::jsonb NOT NULL
);


--
-- Name: fit_dimension_evidence; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fit_dimension_evidence (
    fit_assessment_id uuid NOT NULL,
    dimension text NOT NULL,
    evidence_id uuid NOT NULL
);


--
-- Name: institutions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.institutions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    canonical_name text NOT NULL,
    normalized_name text NOT NULL,
    country_code character varying(2),
    city text,
    website_url text,
    domain text,
    institution_type text,
    authority_score numeric(5,2) DEFAULT '0'::numeric,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: intakes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.intakes (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    program_id uuid NOT NULL,
    intake_label text NOT NULL,
    intake_year smallint NOT NULL,
    start_date date,
    application_deadline date,
    deadline_type text,
    status text DEFAULT 'OPEN'::text,
    evidence_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: monitor_snapshots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.monitor_snapshots (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    subscription_id uuid NOT NULL,
    field_key text NOT NULL,
    old_value jsonb,
    new_value jsonb,
    change_type text NOT NULL,
    evidence_ids jsonb DEFAULT '[]'::jsonb NOT NULL,
    material_change boolean DEFAULT false NOT NULL,
    checked_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: monitor_subscriptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.monitor_subscriptions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    profile_id uuid NOT NULL,
    program_id uuid,
    field_key text NOT NULL,
    frequency text DEFAULT 'WEEKLY'::text NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    last_checked_at timestamp with time zone,
    next_check_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    type text NOT NULL,
    title text NOT NULL,
    body text NOT NULL,
    link text,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    email_status text DEFAULT 'PENDING'::text NOT NULL,
    email_sent_at timestamp with time zone,
    read_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: profile_preferences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile_preferences (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    profile_id uuid NOT NULL,
    preferred_countries jsonb DEFAULT '[]'::jsonb NOT NULL,
    excluded_countries jsonb DEFAULT '[]'::jsonb NOT NULL,
    preferred_cities jsonb DEFAULT '[]'::jsonb NOT NULL,
    preferred_degree_types jsonb DEFAULT '[]'::jsonb NOT NULL,
    preferred_fields jsonb DEFAULT '[]'::jsonb NOT NULL,
    target_intakes jsonb DEFAULT '[]'::jsonb NOT NULL,
    preferred_language text,
    research_preference text,
    career_market_importance numeric(5,2),
    max_distance_preference text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: programs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.programs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    institution_id uuid NOT NULL,
    canonical_name text NOT NULL,
    normalized_name text NOT NULL,
    degree_type text,
    field_of_study text,
    specialization text,
    city text,
    country_code character varying(2),
    language text,
    official_url text,
    duration_months integer,
    tuition_amount numeric(14,2),
    tuition_currency character varying(3),
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    first_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    last_verified_at timestamp with time zone,
    active boolean DEFAULT true NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: requirement_versions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.requirement_versions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    requirement_id uuid NOT NULL,
    value jsonb NOT NULL,
    status public.requirement_status NOT NULL,
    valid_from timestamp with time zone DEFAULT now() NOT NULL,
    valid_to timestamp with time zone,
    change_reason text,
    evidence_id uuid
);


--
-- Name: requirements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.requirements (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    program_id uuid NOT NULL,
    requirement_type text NOT NULL,
    title text NOT NULL,
    normalized_key text NOT NULL,
    operator text,
    value jsonb NOT NULL,
    mandatory boolean DEFAULT true NOT NULL,
    applies_to jsonb DEFAULT '{}'::jsonb NOT NULL,
    status public.requirement_status DEFAULT 'UNKNOWN'::public.requirement_status NOT NULL,
    first_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    last_verified_at timestamp with time zone
);


--
-- Name: research_plan_steps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.research_plan_steps (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    research_plan_id uuid NOT NULL,
    step_key text NOT NULL,
    service_name text NOT NULL,
    status public.run_status DEFAULT 'QUEUED'::public.run_status NOT NULL,
    input jsonb DEFAULT '{}'::jsonb NOT NULL,
    output jsonb DEFAULT '{}'::jsonb NOT NULL,
    search_run_ids jsonb DEFAULT '[]'::jsonb NOT NULL,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    error_message text
);


--
-- Name: research_plans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.research_plans (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    profile_id uuid NOT NULL,
    status public.run_status DEFAULT 'QUEUED'::public.run_status NOT NULL,
    requested_goal jsonb NOT NULL,
    planned_queries jsonb DEFAULT '[]'::jsonb NOT NULL,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    error_message text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    mode text DEFAULT 'live'::text NOT NULL
);


--
-- Name: risk_evidence; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.risk_evidence (
    risk_id uuid NOT NULL,
    evidence_id uuid NOT NULL
);


--
-- Name: risks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.risks (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    fit_assessment_id uuid,
    profile_id uuid NOT NULL,
    program_id uuid,
    risk_type text NOT NULL,
    severity public.risk_severity NOT NULL,
    title text NOT NULL,
    reason text NOT NULL,
    recommended_action text,
    status public.risk_status DEFAULT 'OPEN'::public.risk_status NOT NULL,
    confidence public.confidence_level DEFAULT 'MEDIUM'::public.confidence_level NOT NULL,
    detected_at timestamp with time zone DEFAULT now() NOT NULL,
    resolved_at timestamp with time zone,
    requirement_id uuid
);


--
-- Name: roadmap_tasks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roadmap_tasks (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    strategy_run_id uuid NOT NULL,
    profile_id uuid NOT NULL,
    program_id uuid,
    title text NOT NULL,
    description text,
    task_type text NOT NULL,
    due_date date,
    priority integer DEFAULT 3,
    status public.task_status DEFAULT 'TODO'::public.task_status NOT NULL,
    evidence_ids jsonb DEFAULT '[]'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone
);


--
-- Name: saved_programs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.saved_programs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    profile_id uuid NOT NULL,
    program_id uuid NOT NULL,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: search_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.search_results (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    search_run_id uuid NOT NULL,
    source_id uuid,
    "position" integer,
    result_type text,
    title text,
    snippet text,
    displayed_url text,
    result_url text,
    raw_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    content_hash text,
    retrieved_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: search_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.search_runs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid,
    engine text NOT NULL,
    query text NOT NULL,
    parameters jsonb DEFAULT '{}'::jsonb NOT NULL,
    serpapi_search_id text,
    status public.run_status DEFAULT 'RUNNING'::public.run_status NOT NULL,
    requested_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone,
    duration_ms integer,
    result_count integer,
    cache_hit boolean DEFAULT false,
    error_code text,
    error_message text
);


--
-- Name: skills; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.skills (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    profile_id uuid NOT NULL,
    skill_name text NOT NULL,
    proficiency text,
    months_experience integer,
    source text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: sources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sources (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    url text NOT NULL,
    canonical_url text NOT NULL,
    domain text NOT NULL,
    title text,
    source_authority public.source_authority DEFAULT 'UNKNOWN'::public.source_authority NOT NULL,
    publisher text,
    country_code character varying(2),
    source_type text,
    first_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    last_seen_at timestamp with time zone
);


--
-- Name: strategy_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.strategy_runs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    profile_id uuid NOT NULL,
    research_plan_id uuid,
    status public.run_status DEFAULT 'RUNNING'::public.run_status NOT NULL,
    scoring_version text NOT NULL,
    strategy_version text NOT NULL,
    summary text,
    plan_health_score numeric(5,2),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone
);


--
-- Name: student_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student_profiles (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    current_degree text,
    field_of_study text,
    institution_name text,
    institution_country_code character varying(2),
    graduation_year smallint,
    cgpa numeric(5,2),
    cgpa_scale numeric(5,2),
    percentage numeric(5,2),
    backlogs integer DEFAULT 0,
    total_experience_months integer DEFAULT 0,
    budget_currency character varying(3) DEFAULT 'INR'::character varying,
    total_budget_amount numeric(14,2),
    annual_budget_amount numeric(14,2),
    tuition_budget_amount numeric(14,2),
    scholarship_dependence boolean DEFAULT false,
    career_goal text,
    profile_completion numeric(5,2) DEFAULT '0'::numeric,
    onboarding_version text DEFAULT 'v1'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: test_scores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.test_scores (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    profile_id uuid NOT NULL,
    test_type text NOT NULL,
    overall_score numeric(8,3),
    section_scores jsonb DEFAULT '{}'::jsonb NOT NULL,
    test_date date,
    expiry_date date,
    status text DEFAULT 'VALID'::text,
    evidence_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email text NOT NULL,
    full_name text,
    role public.user_role DEFAULT 'STUDENT'::public.user_role NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    password_hash text,
    password_changed_at timestamp with time zone,
    email_verified_at timestamp with time zone
);


--
-- Name: alembic_version alembic_version_pkc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alembic_version
    ADD CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num);


--
-- Name: application_plans application_plans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_plans
    ADD CONSTRAINT application_plans_pkey PRIMARY KEY (id);


--
-- Name: application_plans application_plans_strategy_run_id_program_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_plans
    ADD CONSTRAINT application_plans_strategy_run_id_program_id_key UNIQUE (strategy_run_id, program_id);


--
-- Name: auth_tokens auth_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_tokens
    ADD CONSTRAINT auth_tokens_pkey PRIMARY KEY (id);


--
-- Name: auth_tokens auth_tokens_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_tokens
    ADD CONSTRAINT auth_tokens_token_hash_key UNIQUE (token_hash);


--
-- Name: counterfactual_runs counterfactual_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.counterfactual_runs
    ADD CONSTRAINT counterfactual_runs_pkey PRIMARY KEY (id);


--
-- Name: countries countries_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.countries
    ADD CONSTRAINT countries_name_key UNIQUE (name);


--
-- Name: countries countries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.countries
    ADD CONSTRAINT countries_pkey PRIMARY KEY (code);


--
-- Name: documents documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (id);


--
-- Name: education_records education_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.education_records
    ADD CONSTRAINT education_records_pkey PRIMARY KEY (id);


--
-- Name: education_subjects education_subjects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.education_subjects
    ADD CONSTRAINT education_subjects_pkey PRIMARY KEY (id);


--
-- Name: eligibility_assessments eligibility_assessments_fit_assessment_id_requirement_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eligibility_assessments
    ADD CONSTRAINT eligibility_assessments_fit_assessment_id_requirement_id_key UNIQUE (fit_assessment_id, requirement_id);


--
-- Name: eligibility_assessments eligibility_assessments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eligibility_assessments
    ADD CONSTRAINT eligibility_assessments_pkey PRIMARY KEY (id);


--
-- Name: eligibility_evidence eligibility_evidence_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eligibility_evidence
    ADD CONSTRAINT eligibility_evidence_pkey PRIMARY KEY (eligibility_assessment_id, evidence_id);


--
-- Name: evidence_conflict_members evidence_conflict_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence_conflict_members
    ADD CONSTRAINT evidence_conflict_members_pkey PRIMARY KEY (conflict_id, evidence_id);


--
-- Name: evidence_conflicts evidence_conflicts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence_conflicts
    ADD CONSTRAINT evidence_conflicts_pkey PRIMARY KEY (id);


--
-- Name: evidence evidence_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence
    ADD CONSTRAINT evidence_pkey PRIMARY KEY (id);


--
-- Name: experiences experiences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.experiences
    ADD CONSTRAINT experiences_pkey PRIMARY KEY (id);


--
-- Name: fit_assessments fit_assessments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fit_assessments
    ADD CONSTRAINT fit_assessments_pkey PRIMARY KEY (id);


--
-- Name: fit_dimension_evidence fit_dimension_evidence_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fit_dimension_evidence
    ADD CONSTRAINT fit_dimension_evidence_pkey PRIMARY KEY (fit_assessment_id, dimension, evidence_id);


--
-- Name: institutions institutions_normalized_name_country_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.institutions
    ADD CONSTRAINT institutions_normalized_name_country_code_key UNIQUE (normalized_name, country_code);


--
-- Name: institutions institutions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.institutions
    ADD CONSTRAINT institutions_pkey PRIMARY KEY (id);


--
-- Name: intakes intakes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.intakes
    ADD CONSTRAINT intakes_pkey PRIMARY KEY (id);


--
-- Name: intakes intakes_program_id_intake_label_intake_year_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.intakes
    ADD CONSTRAINT intakes_program_id_intake_label_intake_year_key UNIQUE (program_id, intake_label, intake_year);


--
-- Name: monitor_snapshots monitor_snapshots_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.monitor_snapshots
    ADD CONSTRAINT monitor_snapshots_pkey PRIMARY KEY (id);


--
-- Name: monitor_subscriptions monitor_subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.monitor_subscriptions
    ADD CONSTRAINT monitor_subscriptions_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: profile_preferences profile_preferences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_preferences
    ADD CONSTRAINT profile_preferences_pkey PRIMARY KEY (id);


--
-- Name: programs programs_institution_id_normalized_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programs
    ADD CONSTRAINT programs_institution_id_normalized_name_key UNIQUE (institution_id, normalized_name);


--
-- Name: programs programs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programs
    ADD CONSTRAINT programs_pkey PRIMARY KEY (id);


--
-- Name: requirement_versions requirement_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requirement_versions
    ADD CONSTRAINT requirement_versions_pkey PRIMARY KEY (id);


--
-- Name: requirements requirements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requirements
    ADD CONSTRAINT requirements_pkey PRIMARY KEY (id);


--
-- Name: requirements requirements_program_id_normalized_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requirements
    ADD CONSTRAINT requirements_program_id_normalized_key_key UNIQUE (program_id, normalized_key);


--
-- Name: research_plan_steps research_plan_steps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.research_plan_steps
    ADD CONSTRAINT research_plan_steps_pkey PRIMARY KEY (id);


--
-- Name: research_plan_steps research_plan_steps_research_plan_id_step_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.research_plan_steps
    ADD CONSTRAINT research_plan_steps_research_plan_id_step_key_key UNIQUE (research_plan_id, step_key);


--
-- Name: research_plans research_plans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.research_plans
    ADD CONSTRAINT research_plans_pkey PRIMARY KEY (id);


--
-- Name: risk_evidence risk_evidence_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.risk_evidence
    ADD CONSTRAINT risk_evidence_pkey PRIMARY KEY (risk_id, evidence_id);


--
-- Name: risks risks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.risks
    ADD CONSTRAINT risks_pkey PRIMARY KEY (id);


--
-- Name: roadmap_tasks roadmap_tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roadmap_tasks
    ADD CONSTRAINT roadmap_tasks_pkey PRIMARY KEY (id);


--
-- Name: saved_programs saved_programs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_programs
    ADD CONSTRAINT saved_programs_pkey PRIMARY KEY (id);


--
-- Name: saved_programs saved_programs_profile_id_program_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_programs
    ADD CONSTRAINT saved_programs_profile_id_program_id_key UNIQUE (profile_id, program_id);


--
-- Name: search_results search_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.search_results
    ADD CONSTRAINT search_results_pkey PRIMARY KEY (id);


--
-- Name: search_runs search_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.search_runs
    ADD CONSTRAINT search_runs_pkey PRIMARY KEY (id);


--
-- Name: skills skills_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.skills
    ADD CONSTRAINT skills_pkey PRIMARY KEY (id);


--
-- Name: skills skills_profile_id_skill_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.skills
    ADD CONSTRAINT skills_profile_id_skill_name_key UNIQUE (profile_id, skill_name);


--
-- Name: sources sources_canonical_url_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sources
    ADD CONSTRAINT sources_canonical_url_key UNIQUE (canonical_url);


--
-- Name: sources sources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sources
    ADD CONSTRAINT sources_pkey PRIMARY KEY (id);


--
-- Name: strategy_runs strategy_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategy_runs
    ADD CONSTRAINT strategy_runs_pkey PRIMARY KEY (id);


--
-- Name: student_profiles student_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_profiles
    ADD CONSTRAINT student_profiles_pkey PRIMARY KEY (id);


--
-- Name: student_profiles student_profiles_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_profiles
    ADD CONSTRAINT student_profiles_user_id_key UNIQUE (user_id);


--
-- Name: test_scores test_scores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_scores
    ADD CONSTRAINT test_scores_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_evidence_retrieved; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_evidence_retrieved ON public.evidence USING btree (retrieved_at);


--
-- Name: idx_evidence_subject; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_evidence_subject ON public.evidence USING btree (subject_type, subject_id);


--
-- Name: idx_monitor_next_check; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_monitor_next_check ON public.monitor_subscriptions USING btree (next_check_at) WHERE (enabled = true);


--
-- Name: idx_programs_country_field; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_programs_country_field ON public.programs USING btree (country_code, field_of_study);


--
-- Name: idx_programs_normalized_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_programs_normalized_name ON public.programs USING btree (normalized_name);


--
-- Name: idx_requirements_program; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_requirements_program ON public.requirements USING btree (program_id);


--
-- Name: idx_risks_profile_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_risks_profile_status ON public.risks USING btree (profile_id, status, severity);


--
-- Name: idx_search_runs_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_search_runs_user ON public.search_runs USING btree (user_id, requested_at);


--
-- Name: idx_strategy_profile; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_strategy_profile ON public.strategy_runs USING btree (profile_id, created_at);


--
-- Name: idx_tasks_profile_due; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tasks_profile_due ON public.roadmap_tasks USING btree (profile_id, due_date, status);


--
-- Name: ix_auth_tokens_user_purpose; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_auth_tokens_user_purpose ON public.auth_tokens USING btree (user_id, purpose);


--
-- Name: ix_notifications_user_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_notifications_user_created ON public.notifications USING btree (user_id, created_at);


--
-- Name: institutions institutions_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER institutions_updated_at BEFORE UPDATE ON public.institutions FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: profile_preferences preferences_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER preferences_updated_at BEFORE UPDATE ON public.profile_preferences FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: student_profiles profiles_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER profiles_updated_at BEFORE UPDATE ON public.student_profiles FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: programs programs_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER programs_updated_at BEFORE UPDATE ON public.programs FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: users users_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER users_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: application_plans application_plans_fit_assessment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_plans
    ADD CONSTRAINT application_plans_fit_assessment_id_fkey FOREIGN KEY (fit_assessment_id) REFERENCES public.fit_assessments(id);


--
-- Name: application_plans application_plans_profile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_plans
    ADD CONSTRAINT application_plans_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.student_profiles(id) ON DELETE CASCADE;


--
-- Name: application_plans application_plans_program_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_plans
    ADD CONSTRAINT application_plans_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id);


--
-- Name: application_plans application_plans_strategy_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_plans
    ADD CONSTRAINT application_plans_strategy_run_id_fkey FOREIGN KEY (strategy_run_id) REFERENCES public.strategy_runs(id) ON DELETE CASCADE;


--
-- Name: auth_tokens auth_tokens_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_tokens
    ADD CONSTRAINT auth_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: counterfactual_runs counterfactual_runs_base_strategy_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.counterfactual_runs
    ADD CONSTRAINT counterfactual_runs_base_strategy_run_id_fkey FOREIGN KEY (base_strategy_run_id) REFERENCES public.strategy_runs(id);


--
-- Name: counterfactual_runs counterfactual_runs_profile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.counterfactual_runs
    ADD CONSTRAINT counterfactual_runs_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.student_profiles(id) ON DELETE CASCADE;


--
-- Name: documents documents_profile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.student_profiles(id) ON DELETE CASCADE;


--
-- Name: education_records education_records_profile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.education_records
    ADD CONSTRAINT education_records_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.student_profiles(id) ON DELETE CASCADE;


--
-- Name: education_subjects education_subjects_education_record_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.education_subjects
    ADD CONSTRAINT education_subjects_education_record_id_fkey FOREIGN KEY (education_record_id) REFERENCES public.education_records(id) ON DELETE CASCADE;


--
-- Name: eligibility_assessments eligibility_assessments_fit_assessment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eligibility_assessments
    ADD CONSTRAINT eligibility_assessments_fit_assessment_id_fkey FOREIGN KEY (fit_assessment_id) REFERENCES public.fit_assessments(id) ON DELETE CASCADE;


--
-- Name: eligibility_assessments eligibility_assessments_requirement_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eligibility_assessments
    ADD CONSTRAINT eligibility_assessments_requirement_id_fkey FOREIGN KEY (requirement_id) REFERENCES public.requirements(id);


--
-- Name: eligibility_evidence eligibility_evidence_eligibility_assessment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eligibility_evidence
    ADD CONSTRAINT eligibility_evidence_eligibility_assessment_id_fkey FOREIGN KEY (eligibility_assessment_id) REFERENCES public.eligibility_assessments(id) ON DELETE CASCADE;


--
-- Name: eligibility_evidence eligibility_evidence_evidence_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eligibility_evidence
    ADD CONSTRAINT eligibility_evidence_evidence_id_fkey FOREIGN KEY (evidence_id) REFERENCES public.evidence(id);


--
-- Name: evidence_conflict_members evidence_conflict_members_conflict_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence_conflict_members
    ADD CONSTRAINT evidence_conflict_members_conflict_id_fkey FOREIGN KEY (conflict_id) REFERENCES public.evidence_conflicts(id) ON DELETE CASCADE;


--
-- Name: evidence_conflict_members evidence_conflict_members_evidence_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence_conflict_members
    ADD CONSTRAINT evidence_conflict_members_evidence_id_fkey FOREIGN KEY (evidence_id) REFERENCES public.evidence(id) ON DELETE CASCADE;


--
-- Name: evidence_conflicts evidence_conflicts_preferred_evidence_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence_conflicts
    ADD CONSTRAINT evidence_conflicts_preferred_evidence_id_fkey FOREIGN KEY (preferred_evidence_id) REFERENCES public.evidence(id);


--
-- Name: evidence evidence_search_result_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence
    ADD CONSTRAINT evidence_search_result_id_fkey FOREIGN KEY (search_result_id) REFERENCES public.search_results(id);


--
-- Name: evidence evidence_source_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evidence
    ADD CONSTRAINT evidence_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.sources(id);


--
-- Name: experiences experiences_profile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.experiences
    ADD CONSTRAINT experiences_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.student_profiles(id) ON DELETE CASCADE;


--
-- Name: fit_assessments fit_assessments_profile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fit_assessments
    ADD CONSTRAINT fit_assessments_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.student_profiles(id) ON DELETE CASCADE;


--
-- Name: fit_assessments fit_assessments_program_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fit_assessments
    ADD CONSTRAINT fit_assessments_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id) ON DELETE CASCADE;


--
-- Name: fit_assessments fit_assessments_research_plan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fit_assessments
    ADD CONSTRAINT fit_assessments_research_plan_id_fkey FOREIGN KEY (research_plan_id) REFERENCES public.research_plans(id) ON DELETE CASCADE;


--
-- Name: fit_dimension_evidence fit_dimension_evidence_evidence_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fit_dimension_evidence
    ADD CONSTRAINT fit_dimension_evidence_evidence_id_fkey FOREIGN KEY (evidence_id) REFERENCES public.evidence(id);


--
-- Name: fit_dimension_evidence fit_dimension_evidence_fit_assessment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fit_dimension_evidence
    ADD CONSTRAINT fit_dimension_evidence_fit_assessment_id_fkey FOREIGN KEY (fit_assessment_id) REFERENCES public.fit_assessments(id) ON DELETE CASCADE;


--
-- Name: institutions institutions_country_code_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.institutions
    ADD CONSTRAINT institutions_country_code_fkey FOREIGN KEY (country_code) REFERENCES public.countries(code);


--
-- Name: intakes intakes_program_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.intakes
    ADD CONSTRAINT intakes_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id) ON DELETE CASCADE;


--
-- Name: monitor_snapshots monitor_snapshots_subscription_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.monitor_snapshots
    ADD CONSTRAINT monitor_snapshots_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.monitor_subscriptions(id) ON DELETE CASCADE;


--
-- Name: monitor_subscriptions monitor_subscriptions_profile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.monitor_subscriptions
    ADD CONSTRAINT monitor_subscriptions_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.student_profiles(id) ON DELETE CASCADE;


--
-- Name: monitor_subscriptions monitor_subscriptions_program_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.monitor_subscriptions
    ADD CONSTRAINT monitor_subscriptions_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id) ON DELETE CASCADE;


--
-- Name: notifications notifications_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: profile_preferences profile_preferences_profile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_preferences
    ADD CONSTRAINT profile_preferences_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.student_profiles(id) ON DELETE CASCADE;


--
-- Name: programs programs_country_code_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programs
    ADD CONSTRAINT programs_country_code_fkey FOREIGN KEY (country_code) REFERENCES public.countries(code);


--
-- Name: programs programs_institution_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programs
    ADD CONSTRAINT programs_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.institutions(id);


--
-- Name: requirement_versions requirement_versions_requirement_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requirement_versions
    ADD CONSTRAINT requirement_versions_requirement_id_fkey FOREIGN KEY (requirement_id) REFERENCES public.requirements(id) ON DELETE CASCADE;


--
-- Name: requirements requirements_program_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requirements
    ADD CONSTRAINT requirements_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id) ON DELETE CASCADE;


--
-- Name: research_plan_steps research_plan_steps_research_plan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.research_plan_steps
    ADD CONSTRAINT research_plan_steps_research_plan_id_fkey FOREIGN KEY (research_plan_id) REFERENCES public.research_plans(id) ON DELETE CASCADE;


--
-- Name: research_plans research_plans_profile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.research_plans
    ADD CONSTRAINT research_plans_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.student_profiles(id) ON DELETE CASCADE;


--
-- Name: risk_evidence risk_evidence_evidence_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.risk_evidence
    ADD CONSTRAINT risk_evidence_evidence_id_fkey FOREIGN KEY (evidence_id) REFERENCES public.evidence(id);


--
-- Name: risk_evidence risk_evidence_risk_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.risk_evidence
    ADD CONSTRAINT risk_evidence_risk_id_fkey FOREIGN KEY (risk_id) REFERENCES public.risks(id) ON DELETE CASCADE;


--
-- Name: risks risks_fit_assessment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.risks
    ADD CONSTRAINT risks_fit_assessment_id_fkey FOREIGN KEY (fit_assessment_id) REFERENCES public.fit_assessments(id) ON DELETE CASCADE;


--
-- Name: risks risks_profile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.risks
    ADD CONSTRAINT risks_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.student_profiles(id) ON DELETE CASCADE;


--
-- Name: risks risks_program_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.risks
    ADD CONSTRAINT risks_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id) ON DELETE CASCADE;


--
-- Name: risks risks_requirement_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.risks
    ADD CONSTRAINT risks_requirement_id_fkey FOREIGN KEY (requirement_id) REFERENCES public.requirements(id) ON DELETE SET NULL;


--
-- Name: roadmap_tasks roadmap_tasks_profile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roadmap_tasks
    ADD CONSTRAINT roadmap_tasks_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.student_profiles(id) ON DELETE CASCADE;


--
-- Name: roadmap_tasks roadmap_tasks_program_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roadmap_tasks
    ADD CONSTRAINT roadmap_tasks_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id) ON DELETE CASCADE;


--
-- Name: roadmap_tasks roadmap_tasks_strategy_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roadmap_tasks
    ADD CONSTRAINT roadmap_tasks_strategy_run_id_fkey FOREIGN KEY (strategy_run_id) REFERENCES public.strategy_runs(id) ON DELETE CASCADE;


--
-- Name: saved_programs saved_programs_profile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_programs
    ADD CONSTRAINT saved_programs_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.student_profiles(id) ON DELETE CASCADE;


--
-- Name: saved_programs saved_programs_program_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_programs
    ADD CONSTRAINT saved_programs_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.programs(id);


--
-- Name: search_results search_results_search_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.search_results
    ADD CONSTRAINT search_results_search_run_id_fkey FOREIGN KEY (search_run_id) REFERENCES public.search_runs(id) ON DELETE CASCADE;


--
-- Name: search_results search_results_source_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.search_results
    ADD CONSTRAINT search_results_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.sources(id);


--
-- Name: search_runs search_runs_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.search_runs
    ADD CONSTRAINT search_runs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: skills skills_profile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.skills
    ADD CONSTRAINT skills_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.student_profiles(id) ON DELETE CASCADE;


--
-- Name: strategy_runs strategy_runs_profile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategy_runs
    ADD CONSTRAINT strategy_runs_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.student_profiles(id) ON DELETE CASCADE;


--
-- Name: strategy_runs strategy_runs_research_plan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategy_runs
    ADD CONSTRAINT strategy_runs_research_plan_id_fkey FOREIGN KEY (research_plan_id) REFERENCES public.research_plans(id);


--
-- Name: student_profiles student_profiles_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_profiles
    ADD CONSTRAINT student_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: test_scores test_scores_profile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_scores
    ADD CONSTRAINT test_scores_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.student_profiles(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict xs1kk4dWReqbh2lAO1443sEyeIIobTtgnJzRck4GUb7DNPI3gpoKQYZF4H0YuCo


-- Alembic version at export time (3e58d2140fc9).
INSERT INTO public.alembic_version (version_num) VALUES ('3e58d2140fc9');
