"""initial schema

Revision ID: 13a74ba738c5
Revises: 
Create Date: 2026-10-07 18:58:54.966866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13a74ba738c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('source_authority', sa.Enum('OFFICIAL_UNIVERSITY', 'OFFICIAL_GOVERNMENT', 'OFFICIAL_ORGANIZATION', 'ACCREDITED_BODY', 'CREDIBLE_SECONDARY', 'NEWS', 'FORUM_SOCIAL', 'UNKNOWN', name='source_authority'), server_default='UNKNOWN', nullable=False),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('source_type', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_url')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('STUDENT', 'ADMIN', name='user_role'), server_default='STUDENT', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('institutions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('institution_type', sa.Text(), nullable=True),
    sa.Column('authority_score', sa.Numeric(precision=5, scale=2), server_default='0', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name', 'country_code')
    )
    op.create_table('search_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('engine', sa.Text(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('serpapi_search_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED', 'CANCELLED', name='run_status'), server_default='RUNNING', nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_search_runs_user', 'search_runs', ['user_id', 'requested_at'], unique=False)
    op.create_table('student_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_degree', sa.Text(), nullable=True),
    sa.Column('field_of_study', sa.Text(), nullable=True),
    sa.Column('institution_name', sa.Text(), nullable=True),
    sa.Column('institution_country_code', sa.String(length=2), nullable=True),
    sa.Column('graduation_year', sa.SmallInteger(), nullable=True),
    sa.Column('cgpa', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cgpa_scale', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('backlogs', sa.Integer(), server_default='0', nullable=True),
    sa.Column('total_experience_months', sa.Integer(), server_default='0', nullable=True),
    sa.Column('budget_currency', sa.String(length=3), server_default='INR', nullable=True),
    sa.Column('total_budget_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('annual_budget_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tuition_budget_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('scholarship_dependence', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('career_goal', sa.Text(), nullable=True),
    sa.Column('profile_completion', sa.Numeric(precision=5, scale=2), server_default='0', nullable=True),
    sa.Column('onboarding_version', sa.Text(), server_default='v1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'DONE', 'BLOCKED', 'SKIPPED', name='task_status'), server_default='TODO', nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('institution_name', sa.Text(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('degree', sa.Text(), nullable=False),
    sa.Column('field_of_study', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('grade_value', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('grade_scale', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('grade_type', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiences',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('experience_type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('organization', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_preferences',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('preferred_countries', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('excluded_countries', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('preferred_cities', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('preferred_degree_types', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('preferred_fields', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('target_intakes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('preferred_language', sa.Text(), nullable=True),
    sa.Column('research_preference', sa.Text(), nullable=True),
    sa.Column('career_market_importance', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_distance_preference', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('degree_type', sa.Text(), nullable=True),
    sa.Column('field_of_study', sa.Text(), nullable=True),
    sa.Column('specialization', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('official_url', sa.Text(), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('tuition_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tuition_currency', sa.String(length=3), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'normalized_name')
    )
    op.create_index('idx_programs_country_field', 'programs', ['country_code', 'field_of_study'], unique=False)
    op.create_index('idx_programs_normalized_name', 'programs', ['normalized_name'], unique=False)
    op.create_table('research_plans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED', 'CANCELLED', name='run_status'), server_default='QUEUED', nullable=False),
    sa.Column('requested_goal', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('planned_queries', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('search_run_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('result_type', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('displayed_url', sa.Text(), nullable=True),
    sa.Column('result_url', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['search_run_id'], ['search_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('skill_name', sa.Text(), nullable=False),
    sa.Column('proficiency', sa.Text(), nullable=True),
    sa.Column('months_experience', sa.Integer(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'skill_name')
    )
    op.create_table('test_scores',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('test_type', sa.Text(), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('section_scores', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('test_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Text(), server_default='VALID', nullable=True),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education_subjects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('education_record_id', sa.UUID(), nullable=False),
    sa.Column('subject_name', sa.Text(), nullable=False),
    sa.Column('credits', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('grade_value', sa.Text(), nullable=True),
    sa.Column('normalized_subject', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['education_record_id'], ['education_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('search_result_id', sa.UUID(), nullable=True),
    sa.Column('claim_type', sa.Text(), nullable=False),
    sa.Column('subject_type', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('normalized_claim', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('extracted_value', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('authority_score', sa.Numeric(precision=5, scale=2), server_default='0', nullable=True),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidence_level'), server_default='LOW', nullable=False),
    sa.Column('status', sa.Enum('CURRENT', 'STALE', 'CONFLICTING', 'UNAVAILABLE', name='evidence_status'), server_default='CURRENT', nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('freshness_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('conflict_group_id', sa.UUID(), nullable=True),
    sa.Column('extraction_model', sa.Text(), nullable=True),
    sa.Column('extraction_version', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['search_result_id'], ['search_results.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_evidence_retrieved', 'evidence', ['retrieved_at'], unique=False)
    op.create_index('idx_evidence_subject', 'evidence', ['subject_type', 'subject_id'], unique=False)
    op.create_table('fit_assessments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('research_plan_id', sa.UUID(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('academic_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('prerequisite_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('language_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('financial_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('career_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('timing_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('evidence_confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('scoring_version', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_plan_id'], ['research_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intakes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('intake_label', sa.Text(), nullable=False),
    sa.Column('intake_year', sa.SmallInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('deadline_type', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='OPEN', nullable=True),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'intake_label', 'intake_year')
    )
    op.create_table('monitor_subscriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=True),
    sa.Column('field_key', sa.Text(), nullable=False),
    sa.Column('frequency', sa.Text(), server_default='WEEKLY', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_monitor_next_check', 'monitor_subscriptions', ['next_check_at'], unique=False, postgresql_where=sa.text('enabled = TRUE'))
    op.create_table('requirements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('requirement_type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('normalized_key', sa.Text(), nullable=False),
    sa.Column('operator', sa.Text(), nullable=True),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mandatory', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('applies_to', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.Enum('SATISFIED', 'PARTIAL', 'NOT_SATISFIED', 'UNKNOWN', 'NOT_APPLICABLE', 'CONFLICTING', 'NEEDS_VERIFICATION', name='requirement_status'), server_default='UNKNOWN', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'normalized_key')
    )
    op.create_index('idx_requirements_program', 'requirements', ['program_id'], unique=False)
    op.create_table('research_plan_steps',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('research_plan_id', sa.UUID(), nullable=False),
    sa.Column('step_key', sa.Text(), nullable=False),
    sa.Column('service_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED', 'CANCELLED', name='run_status'), server_default='QUEUED', nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('search_run_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['research_plan_id'], ['research_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('research_plan_id', 'step_key')
    )
    op.create_table('saved_programs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'program_id')
    )
    op.create_table('strategy_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('research_plan_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED', 'CANCELLED', name='run_status'), server_default='RUNNING', nullable=False),
    sa.Column('scoring_version', sa.Text(), nullable=False),
    sa.Column('strategy_version', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('plan_health_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_plan_id'], ['research_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_strategy_profile', 'strategy_runs', ['profile_id', 'created_at'], unique=False)
    op.create_table('application_plans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('strategy_run_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('REACH', 'TARGET', 'LOWER_RISK', name='program_category'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('fit_assessment_id', sa.UUID(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('estimated_cost', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('next_deadline', sa.Date(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='PLANNED', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fit_assessment_id'], ['fit_assessments.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['strategy_run_id'], ['strategy_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_run_id', 'program_id')
    )
    op.create_table('counterfactual_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('base_strategy_run_id', sa.UUID(), nullable=True),
    sa.Column('scenario_name', sa.Text(), nullable=False),
    sa.Column('modified_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_strategy_run_id'], ['strategy_runs.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eligibility_assessments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('fit_assessment_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('SATISFIED', 'PARTIAL', 'NOT_SATISFIED', 'UNKNOWN', 'NOT_APPLICABLE', 'CONFLICTING', 'NEEDS_VERIFICATION', name='requirement_status'), nullable=False),
    sa.Column('matched_value', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('expected_value', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidence_level'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fit_assessment_id'], ['fit_assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fit_assessment_id', 'requirement_id')
    )
    op.create_table('evidence_conflicts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('conflict_key', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('resolution_status', sa.Text(), server_default='UNRESOLVED', nullable=False),
    sa.Column('preferred_evidence_id', sa.UUID(), nullable=True),
    sa.Column('resolution_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['preferred_evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fit_dimension_evidence',
    sa.Column('fit_assessment_id', sa.UUID(), nullable=False),
    sa.Column('dimension', sa.Text(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['fit_assessment_id'], ['fit_assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fit_assessment_id', 'dimension', 'evidence_id')
    )
    op.create_table('monitor_snapshots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('field_key', sa.Text(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('change_type', sa.Text(), nullable=False),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('material_change', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['monitor_subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirement_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('SATISFIED', 'PARTIAL', 'NOT_SATISFIED', 'UNKNOWN', 'NOT_APPLICABLE', 'CONFLICTING', 'NEEDS_VERIFICATION', name='requirement_status'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('fit_assessment_id', sa.UUID(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=True),
    sa.Column('risk_type', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='risk_severity'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED', name='risk_status'), server_default='OPEN', nullable=False),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidence_level'), server_default='MEDIUM', nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fit_assessment_id'], ['fit_assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_risks_profile_status', 'risks', ['profile_id', 'status', 'severity'], unique=False)
    op.create_table('roadmap_tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('strategy_run_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.Text(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Integer(), server_default='3', nullable=True),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'DONE', 'BLOCKED', 'SKIPPED', name='task_status'), server_default='TODO', nullable=False),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_run_id'], ['strategy_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_profile_due', 'roadmap_tasks', ['profile_id', 'due_date', 'status'], unique=False)
    op.create_table('eligibility_evidence',
    sa.Column('eligibility_assessment_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['eligibility_assessment_id'], ['eligibility_assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('eligibility_assessment_id', 'evidence_id')
    )
    op.create_table('evidence_conflict_members',
    sa.Column('conflict_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conflict_id'], ['evidence_conflicts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conflict_id', 'evidence_id')
    )
    op.create_table('risk_evidence',
    sa.Column('risk_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('risk_id', 'evidence_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_evidence')
    op.drop_table('evidence_conflict_members')
    op.drop_table('eligibility_evidence')
    op.drop_index('idx_tasks_profile_due', table_name='roadmap_tasks')
    op.drop_table('roadmap_tasks')
    op.drop_index('idx_risks_profile_status', table_name='risks')
    op.drop_table('risks')
    op.drop_table('requirement_versions')
    op.drop_table('monitor_snapshots')
    op.drop_table('fit_dimension_evidence')
    op.drop_table('evidence_conflicts')
    op.drop_table('eligibility_assessments')
    op.drop_table('counterfactual_runs')
    op.drop_table('application_plans')
    op.drop_index('idx_strategy_profile', table_name='strategy_runs')
    op.drop_table('strategy_runs')
    op.drop_table('saved_programs')
    op.drop_table('research_plan_steps')
    op.drop_index('idx_requirements_program', table_name='requirements')
    op.drop_table('requirements')
    op.drop_index('idx_monitor_next_check', table_name='monitor_subscriptions', postgresql_where=sa.text('enabled = TRUE'))
    op.drop_table('monitor_subscriptions')
    op.drop_table('intakes')
    op.drop_table('fit_assessments')
    op.drop_index('idx_evidence_subject', table_name='evidence')
    op.drop_index('idx_evidence_retrieved', table_name='evidence')
    op.drop_table('evidence')
    op.drop_table('education_subjects')
    op.drop_table('test_scores')
    op.drop_table('skills')
    op.drop_table('search_results')
    op.drop_table('research_plans')
    op.drop_index('idx_programs_normalized_name', table_name='programs')
    op.drop_index('idx_programs_country_field', table_name='programs')
    op.drop_table('programs')
    op.drop_table('profile_preferences')
    op.drop_table('experiences')
    op.drop_table('education_records')
    op.drop_table('documents')
    op.drop_table('student_profiles')
    op.drop_index('idx_search_runs_user', table_name='search_runs')
    op.drop_table('search_runs')
    op.drop_table('institutions')
    op.drop_table('users')
    op.drop_table('sources')
    op.drop_table('countries')
    # ### end Alembic commands ###
