/**
 * P1-12 API-contract regression test.
 *
 * The committed `api/openapi.json` (exported from the FastAPI app by
 * `backend/scripts/export_openapi.py`) is the source of truth for the
 * frontend's generated types (`npm run gen:api-types` →
 * `app/lib/api-types.generated.ts`). CI regenerates both artifacts and
 * fails on drift; this test asserts the three pieces stay aligned:
 *
 *  1. the committed spec parses and contains the endpoints the client uses;
 *  2. the generated `paths` interface type-checks against those endpoints
 *     (compile-time — a renamed/removed route breaks `npm run typecheck`);
 *  3. the generated file actually declares every path in the spec
 *     (runtime text coverage of the generated artifact).
 */

import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import type { paths } from "./api-types.generated";

// npm scripts run with the frontend package root as cwd; fall back to the
// repo root when vitest is launched from elsewhere.
const SPEC_PATH = [
  path.resolve(process.cwd(), "../api/openapi.json"),
  path.resolve(process.cwd(), "api/openapi.json"),
  path.resolve(process.cwd(), "../AdmitGraph_Production_Blueprint/api/openapi.json"),
].find((candidate) => existsSync(candidate)) as string;

const GENERATED_PATH = path.join(
  [path.resolve(process.cwd(), "app"), path.resolve(process.cwd(), "frontend/app")].find((dir) =>
    existsSync(path.join(dir, "lib", "api-types.generated.ts"))
  ) as string,
  "lib",
  "api-types.generated.ts"
);

/** Endpoints the frontend client actually calls (see lib/api.ts, lib/api-extra.ts). */
const CLIENT_ENDPOINTS = [
  "/api/v1/auth/login",
  "/api/v1/auth/register",
  "/api/v1/auth/me",
  "/api/v1/auth/forgot",
  "/api/v1/auth/reset",
  "/api/v1/auth/verify-request",
  "/api/v1/auth/verify",
  "/api/v1/me/profile",
  "/api/v1/onboarding/answers",
  "/api/v1/programs",
  "/api/v1/documents",
  "/api/v1/evidence",
  "/api/v1/research/plan",
  "/api/v1/research/runs",
  "/api/v1/health",
  "/api/v1/health/ready",
  "/api/v1/notifications",
] as const;

type GeneratedPaths = keyof paths;
type MissingFromTypes = Exclude<(typeof CLIENT_ENDPOINTS)[number], GeneratedPaths>;

describe("API contract (spec ↔ generated types)", () => {
  const spec = JSON.parse(readFileSync(SPEC_PATH, "utf8")) as {
    openapi: string;
    info: { title: string; version: string };
    paths: Record<string, Record<string, unknown>>;
  };
  const generated = readFileSync(GENERATED_PATH, "utf8");

  it("committed spec is a parseable OpenAPI document", () => {
    expect(spec.openapi).toMatch(/^3\./);
    expect(spec.info.title).toBe("AdmitGraph API");
    expect(Object.keys(spec.paths).length).toBeGreaterThan(30);
  });

  it("spec contains every endpoint the frontend client calls", () => {
    const missing = CLIENT_ENDPOINTS.filter((p) => !(p in spec.paths));
    expect(missing, `endpoints missing from api/openapi.json: ${missing.join(", ")}`).toEqual([]);
  });

  it("generated types cover every client endpoint (compile-time)", () => {
    // If a route is renamed/removed from the FastAPI app, re-exporting the
    // spec makes this assignment fail to type-check under `tsc --noEmit`.
    const missing: MissingFromTypes[] = [];
    expect(missing).toEqual([]);
  });

  it("generated types file declares every path in the spec", () => {
    const undeclared = Object.keys(spec.paths).filter(
      (p) => !generated.includes(`"${p}": {`) // prettier-ignore
    );
    expect(
      undeclared,
      `paths in openapi.json but not in api-types.generated.ts — run \`npm run gen:api-types\`:\n${undeclared.join("\n")}`
    ).toEqual([]);
  });

  it("generated file carries the auto-generated banner", () => {
    expect(generated).toContain("auto-generated by openapi-typescript");
  });
});
